### ISSUE TITLE
Wrong Direct X detected

### ISSUE THREAD

**Issue by y0gg** [xtuaok/ACT_EnmityPlugin#26]
The latest updates detects DX9 but dxdiag tells me that DX 11 is installed.
What can I do to run Enmity ?

ACT Log :
![image](https://user-images.githubusercontent.com/27636984/27518684-cbc2b7b4-59e5-11e7-87c8-b3dbc5dda201.png)
![image](https://user-images.githubusercontent.com/27636984/27518689-e65c856e-59e5-11e7-96ed-2ba3e46023af.png)

**Comment by danakj** [comment]
Change FFXIV to use DX11. https://www.reddit.com/r/ffxiv/comments/3a9x1u/psa_dont_forget_to_turn_on_directx_11_in_the_new/
