### ISSUE TITLE
OverlayPlugin-0.3.3.5 以降のエラー

### ISSUE THREAD

**Issue by fute666** [xtuaok/ACT_EnmityPlugin#4]
新しめのOverlayPluginだと、下記のようなエラーが出てしまいます。
OverlayPlugin-0.3.3.3の場合は正常に動作しています。

■OverlayPlugin-0.3.3.5の場合
起動し動作しますが、下記のログがOverlayPluginのログウインドウに大量に出ます。
2015/03/29 13:24:13: Error: Enmity: System.NullReferenceException: オブジェクト参照がオブジェクト インスタンスに設定されていません。
   場所 Tamagawa.EnmityPlugin.EnmityOverlay.checkProcessId()

■OverlayPlugin-0.3.3.6の場合
下記エラーでOverlay PluginがONにできなくなります。

System.NullReferenceException: オブジェクト参照がオブジェクト インスタンスに設定されていません。
   場所 RainbowMage.OverlayPlugin.OverlayBase`1.Start()
   場所 RainbowMage.OverlayPlugin.PluginMain.RegisterOverlay(IOverlay overlay)
   場所 RainbowMage.OverlayPlugin.ControlPanel.CreateAndRegisterOverlay(IOverlayAddon overlayType, String name)
   場所 RainbowMage.OverlayPlugin.ControlPanel.buttonNewOverlay_Click(Object sender, EventArgs e)
   場所 System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   場所 System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   場所 System.Windows.Forms.Control.WndProc(Message& m)
   場所 System.Windows.Forms.ButtonBase.WndProc(Message& m)
   場所 System.Windows.Forms.Button.WndProc(Message& m)
   場所 System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

**Comment by xtuaok** [comment]
[v1.3.0.1](/xtuaok/ACT_EnmityPlugin/releases/tag/v1.3.0.1) で修正しました
