### ISSUE TITLE
Does not detect DX11 client.

### ISSUE THREAD

**Issue by Renari** [xtuaok/ACT_EnmityPlugin#8]
The enmity plugin does not find ffxiv_dx11.exe when running.

**Comment by xtuaok** [comment]
Fixed in 1.4.0.3

**Comment by Hazado** [comment]
Not detecting DX11 again.
Here is the error inside the Overlay Log.

6/30/2015 10:33:32 AM: Error: Enmity Overlay: Tamagawa.EnmityPlugin.ScanFailedException: Exception of type 'Tamagawa.EnmityPlugin.ScanFailedException' was thrown.
   at Tamagawa.EnmityPlugin.EnmityOverlay.getPointerAddress()
   at Tamagawa.EnmityPlugin.EnmityOverlay.checkProcessId()
6/30/2015 10:33:32 AM: Warning: Enmity Overlay: Could not find FFXIV Process.ID

**Comment by xtuaok** [comment]
on the way

**Comment by xtuaok** [comment]
Please try new release v1.4.0.5

**Comment by Hazado** [comment]
Nope still putting out this error. Do you need me to do anything? 
Here is my log file from FFXIV plugin - http://justpaste.it/m33h 
Below is the log from Overlay plugin
6/30/2015 10:05:54 PM: Warning: Enmity Overlay: Could not find FFXIV Process.ID
6/30/2015 10:05:57 PM: Error: Enmity Overlay: Tamagawa.EnmityPlugin.ScanFailedException: Exception of type 'Tamagawa.EnmityPlugin.ScanFailedException' was thrown.
   at Tamagawa.EnmityPlugin.EnmityOverlay.getPointerAddress()
   at Tamagawa.EnmityPlugin.EnmityOverlay.checkProcessId()

**Comment by xtuaok** [comment]
sorry, i'll retry to fix it.

**Comment by xtuaok** [comment]
could you please try again with EnmityOverlay-1.4.0.5.pre.2.zip ?

**Comment by Hazado** [comment]
Its working again! Thank you
