### ISSUE TITLE
Error adding plugin?

### ISSUE THREAD

**Issue by Zentence** [xtuaok/ACT_EnmityPlugin#9]
"This assembly does not have a class that implements ACT's plugin interface." is the error i get adding the EnmityOverlay.dll to ACT, i have the FFXIV_ACT_Plugin.dll version 1.4.0.5 and OverlayPlugin.dll version 3.3.7. i dont understands why its happening?

**Comment by Zentence** [comment]
might have gotten it to work xD but now it cant find Process ID of FFXIV? specificly the Enmity plugin cant :S since the Parse works...

**Comment by xtuaok** [comment]
Fixed in 1.4.0.3

**Comment by Zentence** [comment]
it only worked when i use the FFXIV_ACT_Plugin version 1.4.0.5 not the new 1.4.0.6?

**Comment by xtuaok** [comment]
you should use 1.4.0.6 for DX11.

**Comment by Zentence** [comment]
well thats weird xD since it dosnt work when i use 1.4.0.6 xD but the enmity plugin works when i use 1.4.0.5 and i use dx11 client lol

**Comment by xtuaok** [comment]
no idea.
